//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S_DDD.Context
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DB_FSTCEntities3 : DbContext
    {
        public DB_FSTCEntities3()
            : base("name=DB_FSTCEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUser> AspNetUsers { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<tb_area_estudos> tb_area_estudos { get; set; }
        public virtual DbSet<tb_confiuracoes> tb_confiuracoes { get; set; }
        public virtual DbSet<tb_fonte_dados> tb_fonte_dados { get; set; }
        public virtual DbSet<tb_pedido_informacao> tb_pedido_informacao { get; set; }
        public virtual DbSet<tb_trabalho_cientifico> tb_trabalho_cientifico { get; set; }
        public virtual DbSet<tb_user> tb_user { get; set; }
        public virtual DbSet<tb_respostas> tb_respostas { get; set; }
        public virtual DbSet<tb_utilidade> tb_utilidade { get; set; }
    }
}
