//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S_DDD.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_area_estudos
    {
        public int id_utilidades { get; set; }
        public string area_estudo { get; set; }
        public Nullable<System.DateTime> data_atulizacao { get; set; }
    }
}
