//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S_DDD.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_trabalho_cientifico
    {
        public int id_trabalho_cientifico { get; set; }
        public string titulo { get; set; }
        public string nome { get; set; }
        public string email { get; set; }
        public string telefone { get; set; }
        public Nullable<System.DateTime> ano_conclusao { get; set; }
        public string tipo_trabalho { get; set; }
        public string instituicao_ensino { get; set; }
        public string curso { get; set; }
        public string resumo { get; set; }
        public string palavra_chave { get; set; }
        public string area_estudo { get; set; }
        public string objectivo_trabalho { get; set; }
        public string metodologia { get; set; }
        public string tematica_principal { get; set; }
        public string possivel_aplicacao { get; set; }
        public string departamento { get; set; }
        public string fonte_utilizada { get; set; }
        public string tipo_doc { get; set; }
        public Nullable<System.DateTime> data_atulizacao { get; set; }
        public byte[] formato_doc { get; set; }
    }
}
