//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace S_DDD.Context
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_utilidade
    {
        public int id_utilidade { get; set; }
        public string utilidade { get; set; }
        public Nullable<System.DateTime> data_atulizacao { get; set; }
        public Nullable<int> id_user { get; set; }
    
        public virtual tb_user tb_user { get; set; }
    }
}
